### PR TITLE
Fix False 100% Rates

### PR DESCRIPTION
**Pull request by SethFalco**
Updates some detections on sites that always returned 100% even when there is no profile there.

The following should hopefully only report %100.00 for legit profiles now, before it could report %100.00 when a profile didn't exist:  
* `https://apps.runescape.com/runemetrics/app/overview/player/{username}`
* `https://fosstodon.org/@{username}`
* `https://gitlab.gnome.org/{username}`
* `https://hub.docker.com/u/{username}`
* `https://linkedin.com/in/{username}/`
* `https://mixcloud.com/{username}`

The following still show %100.00 sometimes when a profile isn't found:  
* `https://fiverr.com/{username}`
* `https://duolingo.com/profile/{username}`

### CODE REVIEW

**Comment by giga-a** [comment]
Thanks for fixing them! - ref 89c0e8b3

They reported Rate: %100 because each of those websites has only one detection that contains`"return": "false"`. Those websites do not have the detected `"string"` when a profile not found, therefore logic is valid and counted!

A detection that has `"return": "false"` is better to be used with more `detections` rather than using it by itself - I will make sure to add more details in the Wiki pages regarding `"return": "false"`

```
https://apps.runescape.com/runemetrics/app/overview/player/{username}
https://fosstodon.org/@{username}
https://gitlab.gnome.org/{username}
https://hub.docker.com/u/{username}
https://linkedin.com/in/{username}/
https://mixcloud.com/{username}
https://fiverr.com

E.g.
"detections": [
  {
    "return": "false",
    "string": "The user account you are looking for is no longer available.",
    "type": "normal"
  }
],
```

There was a piece of code that I removed last week https://github.com/qeeqbox/social-analyzer/commit/8247f23f7b17f675681521af5c6d2c5044b0534d#commitcomment-45595489. This restrict using `"return": "false"` and only allowed for `"return": "true"` in the FindUserProfilesFast tag. I am working on it and I will be pushing some changes in the next update

I will check the fiverr.com & duolingo.com after merging this request!

**Comment by giga-a** [comment]
Are you still having issues with fiverr.com? It seems that you fixed it..

I fixed duolingo.co, but it's limited to slow for now https://github.com/qeeqbox/social-analyzer/commit/cf19373fd4420865b0c3c531ee9848c7b4f6e3f4

**Comment by SethFalco** [comment]
> Are you still having issues with fiverr.com? It seems that you already fixed it..

I apologize about that, I thought it was still having issues but just tested it again now, it does indeed work fine. :thinking: 
Not sure what I did wrong before then, my fault.

**Comment by giga-a** [comment]
No worries!

**Comment by giga-a** [comment]
The new version 2021.V.2.14 allows for back-end detection strength customization

```
var detection_level = {
  "extreme": {
    "types": "normal,advanced,ocr",
    "detections": "true",
    "count":1,
    "found":2
  },
  "high": {
    "types": "normal,advanced,ocr",
    "detections": "true,false",
    "count":1,
    "found":1
  },
  "current":"high"
}

```

Example 
We can change the value of `types` to `normal` meaning: Only `detection` type `normal` is allowed

We can change the value of `detections` to `true` meaning: Exclude reverse `detections` and allow only detection that returns `true`

We can change the value of `count` to `2` meaning: There has to be at least `2 ` `detections` from the available `types` (website entry with one `detection` only won't be processed)

We can also change `found` to 3 meaning: There has to be at least 3 valid logics\triggered detections before calculating `rate` etc..

```
"detections": [
  {
    "return": "false",
    "string": "The user account you",
    "type": "normal"
  }
],
```

**Pull request merged**
