### PR TITLE
Make JSON Formatting Consistent

### PR DESCRIPTION
**Pull request by SethFalco**
This just uses a formatter on the JSON files in the repository, so they all follow the same conventions.

Before some files had 2 space tabs, while others had 4 space tabs, or the way arrays where formatted varied.

### CODE REVIEW

**Comment by giga-a** [comment]
👍 - ref 386fc8d6

**Comment by giga-a** [comment]
Added a small bash script called beautify_json_files.sh
It cleans and formats dict.json, names.json & sites.json

[beautify_json_files.sh](https://github.com/qeeqbox/social-analyzer/blob/main/beautify_json_files.sh)

**Comment by SethFalco** [comment]
> Added a small bash script called beautify_json_files.sh
> It cleans and formats dict.json, names.json & sites.json
> 
> [beautify_json_files.sh](https://github.com/qeeqbox/social-analyzer/blob/main/beautify_json_files.sh)

Just a small question. Since this project is already using Node/NPM, have you considered taking an approach where you add a dev dependencies for linting and formatting instead?

For example, [eslint](https://github.com/eslint/eslint/) or [prettier](https://github.com/prettier/prettier)?
I just think this solution might be cleaner, and it'd keep the solution to depend on project dependencies only and ensure cross-platform compatibility during development?

On another note, if there is going to be a script now for applying subjective formatting automagically, it might be nice to add it as an npm script?

ie in package.json in `scripts`.

`"format": "./beautify_json_files.sh"`

Your choice what you do, just wanted to throw in my opinion.

**Comment by giga-a** [comment]
Great feedback! 

> Just a small question. Since this project is already using Node/NPM, have you considered taking an approach where you add a dev dependencies for linting and formatting instead

I thought of something similar but later I implemented some Macaw's modules that handle the formatting, validating and beautifying automatically. I'm currently updating those modules to handle more file types. I added `beautify_json_files.sh` because JSON files need to be formatted with `jq` otherwise it may break Macaw (At this moment). That script will be removed automatically when I finish updating the modules

**Pull request merged**
