### PR TITLE
Added 30 Websites

### PR DESCRIPTION
**Pull request by SethFalco**
Adds the following sites:
* `https://anilist.co/user/{username}/`
* `https://apps.runescape.com/runemetrics/app/overview/player/{username}`
* `https://www.artstation.com/{username}`
* `https://bintray.com/{username}`
* `https://crowdin.com/profile/{username}`
* `https://coil.com/u/{username}`
* `https://community.bitwarden.com/u/{username}/summary`
* `https://create.arduino.cc/projecthub/{username}`
* `https://www.crunchyroll.com/user/{username}`
* `https://discourse.wicg.io/u/{username}/summary`
* `https://displate.com/{username}/profile`
* `https://www.ebay.co.uk/usr/{username}`
* `https://www.fiverr.com/{username}`
* `https://fosstodon.org/web/accounts/{username}`
* `https://gitlab.gnome.org/{username}`
* `https://plugins.gradle.org/u/{username}`
* `https://help.nextcloud.com/u/{username}/summary`
* `https://www.hexrpg.com/userinfo/{username}`
* `https://hosted.weblate.org/user/{username}/`
* `https://i18n.elypia.org/user/{username}/`
* `https://www.linkedin.com/in/{username}/`
* `https://ninjakiwi.com/profile/{username}`
* `https://nyaa.si/user/{username}`
* `https://opencollective.com/{username}`
* `https://www.slant.co/users/{username}`
* `https://tenor.com/users/{username}`
* `https://tldrlegal.com/users/{username}/`
* `https://translate.jellyfin.org/user/{username}/`
* `https://wiki.vg/User:{username}`
* `https://www.wordnik.com/users/{username}`

### CODE REVIEW

**Comment by giga-a** [comment]
Hey SethFalco! Thanks for your contributions. 
I passed the changes to my Dedicated Testing System

`ID eec92e69-5a68-4e98-b722-ec2fed4b113f`

**Comment by SethFalco** [comment]
Can I just clarify, so I didn't do much the detections since I wasn't 100% sure on it. (Would be great to see a CONTRIBUTING.md added!)

```json
{
  "url": "https://apps.runescape.com/runemetrics/app/overview/player/{username}",
  "detections": [{
      "return": "false",
      "string": "Sorry, that player could not be found",
      "type": "normal"
    }
  ],
  "selected": "false",
  "timeout": 0,
  "implicit": 0,
  "type": "MMORPG"
},
```

Is this correct? So for example to add a detection, I just say if it's a positive or negative response, some text that may appear on that page to determine the response?

**Comment by SethFalco** [comment]
Based on what I've seen, I think / hope I did this correctly. ^-^'
Do let me know if there's anything wrong or if I have to undo that commit, though!

**Comment by giga-a** [comment]
Hey, test passed 

`[Custom Test Passed - detections] -> eec92e69-5a68-4e98-b722-ec2fed4b113f`
 
To answer your question:
Yes, you are able to detect on anything may appear on that page or not. And, your detection is correct :+1: 

```
{
  "url": "https://apps.runescape.com/runemetrics/app/overview/player/{username}",
  "detections": [{
      "return": "false",
      "string": "Sorry, that player could not be found",
      "type": "normal"
    }
  ],
  "selected": "false",
  "timeout": 0,
  "implicit": 0,
  "type": "MMORPG"
},
```

This detection means if `You used Sorry, that player could not be found` is not in the page, then logic is valid and will be counted as +1.

```
  {
    "url": "https://example.com/u/{username}",
    "detections": [
      {
        "return": "false",
        "string": "There's nothing here",
        "type": "normal"
      },
      {
        "return": "true",
        "string": "last_name",
        "type": "normal"
      }
    ],
    "selected": "false",
    "timeout": 0,
    "implicit": 0,
    "type": ""
  }
```

This detection means if `There's nothing here` is not the page, then logic is valid and will be counted as +1. Also, if `last_name` is in the page, then logic is valid and will be counted as +1. So, now we have 2 out 2 detections are valid. 

This project utilizes a custom multi layer detection model. Think of it as: The more detections you have against a target, the better detection rate and results

I will look into CONTRIBUTING.md next week (Keep your eyes open)

**Comment by giga-a** [comment]
Alright! I went over them and I changed few things

`https://coil.com/u/` <- Switched to ocr
`https://opencollective.com` <- Changed to `Not found<` which will prevent it from triggering on `notFound` in the inline json object
`https://www.ebay.co.uk` <- Removed - duplicate
`https://wiki.vg/` <- Removed - duplicate
`https://fosstodon.org`    <- I was not able to verify (I kept it for now)
`https://gitlab.gnome.org`   <- I was not able to verify (I kept it for now)

There is a file named `info` that has some project metadata (version, number detection etc..). I issued a new auto_testing request, at the end of the test it will update the information 👏 

{"version":"",
 "build":"",
 "test":"",
 "websites":"",
 "detections":"",
 "special":"",
 "awaiting_verification":"",
 "auto_testing":""}

**Comment by SethFalco** [comment]
@giga-a 

Sorry about the ebay.co.uk one, didn't realize ebay.com vs ebay.co.uk would be considered a duplicate.
Regarding wiki.vg, are you certain that's a duplicate, though? I don't see it anywhere else in the repository?

**Comment by flawhoodlum1** [comment]
Flaw Hoodlum Entourage @flawhoodlum

**Review by Activate256 — APPROVED** [review]

**Review by Activate256 — APPROVED** [review]

**Comment by giga-a** [comment]
@SethFalco  No worries, there are different tests that run on my testing system. Some of those tests are: Site Status, Name Checking, Similarity Checking & Alexa Metrics. The Name Checking logic goes: If there are multiple entries with the same domain name then, check their interfaces regardless of the top level domains. If matches, then it deletes the new ones. ebay.co.uk and ebay.com produced the same result. So, ebay.co.uk got flagged and deleted (Alexa Metrics test runs after sites.json gets published in this GitHub repo). I'm not entirely sure about wiki.vg, but I will check the logs related to `ec92e69-5a68-4e98-b722-ec2fed4b113f`

**Review by shell4276 — COMMENTED** [review]
Cancel

**Pull request merged**
